import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, AtSign, BriefcaseBusiness, Code2, Command, Cpu, ExternalLink, Mail, Menu, Send, Sparkles, X } from 'lucide-react';
import { aiRoadmap, certificates, education, profile, projects, skills } from './data/portfolioData';

const routeItems = ['home', 'about', 'skills', 'ai', 'projects', 'education', 'certifications', 'contact'];
const navItems = [...routeItems];

function Starfield() {
  const canvasRef = useRef(null);
  useEffect(() => {
    const canvas = canvasRef.current;
    const context = canvas.getContext('2d');
    const stars = Array.from({ length: 150 }, () => ({ x: Math.random(), y: Math.random(), z: Math.random(), size: Math.random() * 1.8 + 0.3 }));
    let frame;
    const resize = () => { canvas.width = window.innerWidth * devicePixelRatio; canvas.height = window.innerHeight * devicePixelRatio; canvas.style.width = `${window.innerWidth}px`; canvas.style.height = `${window.innerHeight}px`; context.setTransform(devicePixelRatio, 0, 0, devicePixelRatio, 0, 0); };
    const draw = () => { context.clearRect(0, 0, window.innerWidth, window.innerHeight); stars.forEach((star) => { star.y -= 0.00012 * (0.4 + star.z); if (star.y < -0.02) star.y = 1.02; context.fillStyle = `rgba(177, 213, 255, ${0.2 + star.z * 0.55})`; context.beginPath(); context.arc(star.x * window.innerWidth, star.y * window.innerHeight, star.size * star.z, 0, Math.PI * 2); context.fill(); }); frame = requestAnimationFrame(draw); };
    resize(); draw(); window.addEventListener('resize', resize);
    return () => { cancelAnimationFrame(frame); window.removeEventListener('resize', resize); };
  }, []);
  return <canvas ref={canvasRef} className="starfield" aria-hidden="true" />;
}

function SectionLabel({ number, children }) { return <div className="section-label"><span>{number}</span><i />{children}</div>; }
function PageAtmosphere({ type }) { return <div className={`page-atmosphere atmosphere-${type}`} aria-hidden="true"><div className="atmosphere-grid" /><div className="atmosphere-glow glow-a" /><div className="atmosphere-glow glow-b" /><div className="atmosphere-lines" /><div className="atmosphere-points">{[1, 2, 3, 4, 5, 6].map((point) => <i key={point} />)}</div></div>; }
function IntelligenceCore() { return <div className="intelligence-core" aria-label="Interactive AI visualization"><div className="core-grid" /><div className="core-ring core-ring-a" /><div className="core-ring core-ring-b" /><div className="core-orbit orbit-top" /><div className="core-orbit orbit-side" /><div className="core-sphere"><div className="core-light" /><span>NH</span></div><i className="core-node node-top" /><i className="core-node node-right" /><i className="core-node node-left" /><i className="core-node node-bottom" /><span className="core-label label-code">DATA / 01</span><span className="core-label label-ai">INTELLIGENCE</span><span className="core-label label-build">BUILDING</span></div>; }

function HomePage({ navigate }) { return <section className="page-view home-page page-enter"><div className="home-copy"><p className="eyebrow"><span className="pulse-dot" />CURRENTLY LEARNING &amp; BUILDING</p><h1>Hi, I'm<br /><span>Nayab</span><em>Nehal Haque</em></h1><p className="hero-role">Aspiring AI Engineer</p><p className="hero-role secondary-role">Computer Science &amp; Engineering Student</p><p className="home-intro">Building my skills in AI, Machine Learning, software development, and intelligent technology.</p><div className="hero-actions"><button className="primary-button" onClick={() => navigate('projects')}>EXPLORE MY WORK <ArrowUpRight size={17} /></button><button className="secondary-button" onClick={() => navigate('contact')}>CONNECT WITH ME</button></div><div className="hero-socials"><a href={profile.github} target="_blank" rel="noreferrer" aria-label="GitHub"><Code2 size={17} /></a><a href={profile.linkedin} target="_blank" rel="noreferrer" aria-label="LinkedIn"><BriefcaseBusiness size={17} /></a><a href={profile.instagram} target="_blank" rel="noreferrer" aria-label="Instagram"><AtSign size={17} /></a></div></div><div className="home-visual"><IntelligenceCore /></div><div className="home-footer"><span>NH. / AI ENGINEERING JOURNEY</span><span>REVA UNIVERSITY / BENGALURU</span></div></section>; }

function AboutPage() { return <section className="page-view about-page page-enter"><SectionLabel number="01">IDENTITY PROFILE</SectionLabel><div className="about-layout"><div className="developer-portrait"><div className="portrait-grid" /><div className="portrait-head"><div className="portrait-eye" /><div className="portrait-eye" /></div><div className="portrait-body"><Cpu size={28} /><span>AI ENGINEER / 01</span></div><span className="portrait-code">CSE<br />REVA<br />BENGALURU</span></div><div className="about-copy"><h2>About <span>Me</span></h2><p>{profile.bio}</p><p>My interests include Artificial Intelligence, Machine Learning, software development, programming, problem solving, web development, Generative AI, and emerging technologies.</p><div className="info-cards"><div><span>EDU</span><small>BRANCH</small><strong>{profile.branch}</strong></div><div><span>UNI</span><small>UNIVERSITY</small><strong>{profile.university}</strong></div><div><span>LOC</span><small>LOCATION</small><strong>{profile.location}</strong></div><div><span>02</span><small>CURRENT STATUS</small><strong>{profile.year}</strong></div><div><span>AI</span><small>CAREER DIRECTION</small><strong>Aspiring AI Engineer</strong></div><div><span>NH</span><small>INTERESTS</small><strong>AI · ML · Software · GenAI</strong></div></div></div></div></section>; }

function SkillsPage({ selectedSkill, setSelectedSkill }) { return <section className="page-view skills-page page-enter"><SectionLabel number="02">SKILL CONSTELLATION</SectionLabel><div className="section-heading split"><div><h2>Learning in <span>orbit.</span></h2><p>Current skills and the foundations being built for a future in intelligent systems.</p></div><span className="micro-label">CLICK A NODE<br />TO FOCUS</span></div><div className="skills-layout"><div className="skills-orbit">{['path-a', 'path-b', 'path-c'].map((path) => <div className={`orbit-path ${path}`} key={path} />)}<div className="orbit-core"><span>NH</span><small>CORE</small></div>{skills.map((skill, index) => <button key={skill.name} className={`skill-node node-${index + 1} ${selectedSkill.name === skill.name ? 'selected' : ''}`} onClick={() => setSelectedSkill(skill)}>{skill.name}</button>)}</div><div className="skill-detail"><span className="eyebrow">SELECTED NODE / {selectedSkill.type.toUpperCase()}</span><h3>{selectedSkill.name}</h3><p>{selectedSkill.detail}.</p><div className="detail-line"><span>STATUS</span><strong>{selectedSkill.status.toUpperCase()}</strong></div><div className="detail-line"><span>ORBIT</span><strong>{selectedSkill.orbit.toUpperCase()}</strong></div></div></div></section>; }

function AiMlPage() { return <section className="page-view ai-ml-page page-enter"><SectionLabel number="03">AI / MACHINE LEARNING</SectionLabel><div className="section-heading"><h2>Building toward <span>intelligence.</span></h2><p>A structured roadmap that keeps ambition honest: current foundations, active learning, and future exploration.</p></div><div className="status-legend"><span>Current Skills</span><span>Currently Learning</span><span>Exploring</span><span>AI/ML Learning Roadmap</span></div><div className="ai-roadmap">{Object.entries(aiRoadmap).map(([category, items]) => <article className="roadmap-card" key={category}><div className="roadmap-card-top"><Cpu size={18} /><span>{category}</span></div><div className="roadmap-tags">{items.map((item) => <span key={item}>{item}</span>)}</div></article>)}</div></section>; }
function ProjectsPage() { return <section className="page-view projects-page page-enter"><SectionLabel number="05">WORK IN PROGRESS</SectionLabel><div className="section-heading"><h2>Ideas becoming <span>useful.</span></h2><p>Projects will appear here as they move from curiosity to something real. No invented results, just an editable space for honest work.</p></div><div className="project-list">{projects.map((project, index) => <article className="project-row" key={project.title}><div className="project-number">0{index + 1}</div><div className="project-main"><span className="eyebrow">{project.status}</span><h3>{project.title}</h3><p>{project.description}</p><div className="tech-list">{project.technologies.map((tech) => <span key={tech}>{tech}</span>)}</div></div><ArrowUpRight size={20} /></article>)}</div></section>; }
function EducationPage() { return <section className="page-view education-page page-enter"><SectionLabel number="04">TRAJECTORY</SectionLabel><div className="section-heading"><h2>Still in <span>motion.</span></h2><p>A clear path through Computer Science &amp; Engineering at REVA University.</p></div><div className="timeline">{education.map((item, index) => <div className={`timeline-item ${index === 1 ? 'current' : ''}`} key={item.year}><div className="timeline-node"><span>{index === 1 ? 'NOW' : item.year}</span></div><div><span className="timeline-year">{item.year}</span><h3>{item.title}</h3><p>{item.note}</p></div></div>)}</div></section>; }

function CertificatePage() { const [selected, setSelected] = useState(null); useEffect(() => { if (!selected) return undefined; const close = (event) => event.key === 'Escape' && setSelected(null); document.body.style.overflow = 'hidden'; window.addEventListener('keydown', close); return () => { document.body.style.overflow = ''; window.removeEventListener('keydown', close); }; }, [selected]); return <section className="page-view certificates-page page-enter"><SectionLabel number="06">CREDENTIAL ARCHIVE</SectionLabel><div className="certificates-intro"><div><h2>Certifications <span>&amp; Learning</span></h2><p>My certifications will appear here as they are earned. The data structure supports title, issuer, date, credential ID, image, PDF, verification URL, skills, and description.</p></div><strong>{certificates.length.toString().padStart(2, '0')} <small>CERTIFICATIONS</small></strong></div><div className="certificate-grid">{certificates.length ? certificates.map((certificate) => <article className="certificate-card" key={certificate.title}><button className="certificate-preview" onClick={() => setSelected(certificate)}><img src={certificate.image} alt={`${certificate.title} certificate`} /></button><div className="certificate-card-body"><div className="certificate-meta"><span>{certificate.issuer}</span><time>{certificate.date}</time></div><h3>{certificate.title}</h3><p>{certificate.description}</p><button className="text-button" onClick={() => setSelected(certificate)}>VIEW CERTIFICATE <ArrowUpRight size={14} /></button>{certificate.verificationUrl && <a className="verify-link" href={certificate.verificationUrl} target="_blank" rel="noreferrer">VERIFY CERTIFICATE <ExternalLink size={13} /></a>}</div></article>) : <div className="certificate-empty"><Sparkles size={26} /><h3>My certifications will appear here.</h3><p>Add a certificate object to <strong>certificates</strong> in the portfolio data file and it will automatically use this card system.</p></div>}</div>{selected && <div className="certificate-modal" role="dialog" aria-modal="true" onClick={() => setSelected(null)}><div className="certificate-modal-panel" onClick={(event) => event.stopPropagation()}><button className="icon-button modal-close" onClick={() => setSelected(null)} aria-label="Close certificate viewer"><X size={18} /></button><div className="certificate-modal-preview">{selected.image ? <img src={selected.image} alt={selected.title} /> : <span>PREVIEW IMAGE TO BE ADDED</span>}</div><div className="certificate-modal-info"><span className="eyebrow">{selected.issuer}</span><h3>{selected.title}</h3><p>{selected.description}</p>{selected.verificationUrl && <a className="primary-button" href={selected.verificationUrl} target="_blank" rel="noreferrer">VERIFY <ExternalLink size={15} /></a>}</div></div></div>}</section>; }

function SocialLinks() { return <div className="contact-links"><a href={`mailto:${profile.email}`}><Mail size={17} />EMAIL <ArrowUpRight size={14} /></a><a href={profile.github} target="_blank" rel="noreferrer"><Code2 size={17} />GITHUB <ArrowUpRight size={14} /></a><a href={profile.linkedin} target="_blank" rel="noreferrer"><BriefcaseBusiness size={17} />LINKEDIN <ArrowUpRight size={14} /></a><a href={profile.instagram} target="_blank" rel="noreferrer"><AtSign size={17} />INSTAGRAM <ArrowUpRight size={14} /></a></div>; }
function ContactPage({ sent, setSent }) { return <section className="page-view contact-page page-enter"><SectionLabel number="07">OPEN CHANNEL</SectionLabel><div className="contact-layout"><div><h2>Let's <span>Build.</span></h2><p>Let's build something intelligent. For collaboration, project ideas, or a conversation about technology.</p><SocialLinks /><div className="contact-details"><a href={`mailto:${profile.email}`}>{profile.email}</a><a href={profile.github} target="_blank" rel="noreferrer">github.com/nayabhaque786</a><a href={profile.linkedin} target="_blank" rel="noreferrer">linkedin.com/in/nayab-nehal-haque</a><a href={profile.instagram} target="_blank" rel="noreferrer">{profile.instagramHandle}</a></div></div><form className="contact-form" onSubmit={(event) => { event.preventDefault(); setSent(true); }}><div className="form-top"><span>TRANSMISSION FORM</span><span>ENCRYPTED / LOCAL</span></div><label>YOUR NAME<input required placeholder="Enter your name" /></label><label>YOUR EMAIL<input required type="email" placeholder="name@domain.com" /></label><label>MESSAGE<textarea required placeholder="Start a conversation..." rows="3" /></label><button className="primary-button" type="submit">{sent ? 'MESSAGE READY' : 'SEND MESSAGE'} <Send size={16} /></button>{sent && <small className="form-note">Frontend only: email delivery is not configured yet.</small>}</form></div></section>; }

function CommandCenter({ open, close, navigate }) { const [query, setQuery] = useState(''); const commands = ['/home', '/about', '/skills', '/ai', '/projects', '/education', '/certifications', '/contact', '/github', '/linkedin', '/instagram']; const filtered = commands.filter((command) => command.includes(query.toLowerCase())); const execute = (command) => { const page = command.slice(1); if (routeItems.includes(page)) navigate(page); else window.open(profile[page], '_blank', 'noopener,noreferrer'); close(); setQuery(''); }; return <div className={`command-overlay ${open ? 'is-open' : ''}`} aria-hidden={!open}><div className="command-center"><div className="command-top"><span><Command size={16} /> NAYAB COMMAND CENTER</span><button className="icon-button" onClick={close} aria-label="Close command center"><X size={18} /></button></div><div className="command-input"><Command size={18} /><input autoFocus={open} value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search Nayab's portfolio..." /></div><div className="command-list">{filtered.map((command) => <button key={command} onClick={() => execute(command)}><span>{command}</span><small>OPEN</small></button>)}</div></div></div>; }
function App() { const initial = window.location.hash.replace('#/', '') || 'home'; const [active, setActive] = useState(routeItems.includes(initial) ? initial : 'home'); const [menuOpen, setMenuOpen] = useState(false); const [commandOpen, setCommandOpen] = useState(false); const [selectedSkill, setSelectedSkill] = useState(skills[0]); const [sent, setSent] = useState(false); useEffect(() => { const pop = () => setActive(window.location.hash.replace('#/', '') || 'home'); const shortcut = (event) => { if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); setCommandOpen(true); } }; window.addEventListener('popstate', pop); window.addEventListener('keydown', shortcut); return () => { window.removeEventListener('popstate', pop); window.removeEventListener('keydown', shortcut); }; }, []); const navigate = (page) => { window.history.pushState({}, '', `#/${page}`); setActive(page); setMenuOpen(false); window.scrollTo({ top: 0, behavior: 'smooth' }); }; const page = active === 'home' ? <HomePage navigate={navigate} /> : active === 'about' ? <AboutPage /> : active === 'skills' ? <SkillsPage selectedSkill={selectedSkill} setSelectedSkill={setSelectedSkill} /> : active === 'ai' ? <AiMlPage /> : active === 'projects' ? <ProjectsPage /> : active === 'education' ? <EducationPage /> : active === 'certifications' ? <CertificatePage /> : <ContactPage sent={sent} setSent={setSent} />; return <div className="app-shell"><Starfield /><div className="ambient ambient-one" /><div className="ambient ambient-two" /><header className="topbar"><button className="brand" onClick={() => navigate('home')}><span className="brand-mark">NH.</span><span><strong>NAYAB NEHAL HAQUE</strong><small>AI / DIGITAL INTELLIGENCE</small></span></button><button className="command-hint" onClick={() => setCommandOpen(true)}><Command size={13} /> CTRL K</button><button className="menu-toggle icon-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation">{menuOpen ? <X size={20} /> : <Menu size={20} />}</button><nav className={menuOpen ? 'nav-open' : ''}>{navItems.map((item) => <button key={item} className={active === item.replace('/', '') ? 'active' : ''} onClick={() => navigate(item === 'ai/ml' ? 'ai' : item)}>{item}</button>)}</nav><div className="system-status"><span className="pulse-dot" />SYSTEM ONLINE</div></header><main className="page-stage"><PageAtmosphere type={active === 'ai' ? 'skills' : active} />{page}</main><footer><div><strong>NAYAB NEHAL HAQUE</strong><span>Aspiring AI Engineer | Computer Science &amp; Engineering Student</span><span>{profile.university} · {profile.location}</span></div><SocialLinks /><div className="footer-bottom">© 2026 Nayab Nehal Haque. All rights reserved.</div></footer><CommandCenter open={commandOpen} close={() => setCommandOpen(false)} navigate={navigate} /></div>; }

export { App };
